on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jfrog/setup-jfrog-cli@v1
        env:
           JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
      - run: |
          # Ping the server priar
          # jfrog c use priar
          # jfrog rt ping
          
          jfrog rt dl artifacts/
        
